# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nanagong' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 카카오 로그인
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'

  # 구글 로그인
  pod 'GoogleSignIn'

end
